#!/usr/bin/env python3
"""
Chalk-tilt ledger builder for the NPBSide model-vs-book pricing watch.

Background (memory feedback_npbside_chalk_tilt): the model has been running
chalkier than the book on agreement games. Before tuning WIN_DIVISOR / SP-rating
/ park-factor application, we accumulate a per-game ledger of the chalk gap and
the actual outcome to learn whether our extra chalk is *right* (edge) or just
*more* (noise).

Reads every data/grade-{date}.json that carries book lines and emits
data/chalk-tilt-ledger.json — one row per agreement game (model fav == book fav,
where the chalk gap is well-defined) plus a rolling summary. Flip games (model
and book disagree on favorite) are counted separately, not in the chalk rows.

Re-run after each grade-day.py to refresh. Idempotent — fully regenerated each run.

Usage:
    python3 scripts/build-chalk-ledger.py
"""
import json, os, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "chalk-tilt-ledger.json")

def imp(ml):
    if ml is None:
        return None
    return abs(ml) / (abs(ml) + 100) if ml < 0 else 100 / (ml + 100)

def fav_won(g):
    """Did the model/book favorite (same team on agreement rows) actually win?"""
    # actual is "away-home" runs string like "4-2"; matchup is "Away @ Home"
    try:
        a, h = (int(x) for x in str(g["actual"]).split("-"))
    except Exception:
        return None
    away, home = [s.strip() for s in g["matchup"].split("@")]
    winner = home if h > a else (away if a > h else None)
    return None if winner is None else (winner == g["modelFav"])

def main():
    rows, flips, daily = [], [], {}
    for f in sorted(glob.glob(os.path.join(ROOT, "data", "grade-*.json"))):
        date = os.path.basename(f).replace("grade-", "").replace(".json", "")
        d = json.load(open(f))
        for g in d.get("games", []):
            om, bm = g.get("modelFavMl"), g.get("bookFavMl")
            if om is None or bm is None:
                continue  # no book line — skip
            d_day = daily.setdefault(date, {"n": 0, "gaps": [], "weChalkWon": 0,
                                            "weChalkLost": 0, "bkChalkWon": 0, "bkChalkLost": 0})
            if g.get("modelFav") != g.get("bookFav"):
                flips.append({"date": date, "matchup": g["matchup"],
                              "modelFav": g.get("modelFav"), "bookFav": g.get("bookFav"),
                              "favWon": fav_won(g)})
                continue
            gap = (imp(om) - imp(bm)) * 100  # +pp = model chalkier than book
            won = fav_won(g)
            row = {"date": date, "matchup": g["matchup"], "fav": g["modelFav"],
                   "ourMl": om, "bookMl": bm, "chalkGapPp": round(gap, 1),
                   "favWon": won, "sideResult": g.get("sideResult")}
            rows.append(row)
            d_day["n"] += 1
            d_day["gaps"].append(gap)
            if won is not None:
                weChalkier = gap > 0
                if weChalkier and won: d_day["weChalkWon"] += 1
                elif weChalkier and not won: d_day["weChalkLost"] += 1
                elif (not weChalkier) and won: d_day["bkChalkWon"] += 1
                else: d_day["bkChalkLost"] += 1

    # roll up
    for v in daily.values():
        v["meanGapPp"] = round(sum(v["gaps"]) / len(v["gaps"]), 1) if v["gaps"] else None
        del v["gaps"]
    allgaps = [r["chalkGapPp"] for r in rows]
    we_more = [r for r in rows if r["chalkGapPp"] > 0 and r["favWon"] is not None]
    bk_more = [r for r in rows if r["chalkGapPp"] <= 0 and r["favWon"] is not None]
    summary = {
        "nAgreementGames": len(rows),
        "nFlipGames": len(flips),
        "meanGapPp": round(sum(allgaps) / len(allgaps), 1) if allgaps else None,
        "gapRangePp": [round(min(allgaps), 1), round(max(allgaps), 1)] if allgaps else None,
        "whenWeChalkier": {"n": len(we_more),
                           "favWon": sum(1 for r in we_more if r["favWon"]),
                           "favLost": sum(1 for r in we_more if not r["favWon"])},
        "whenBookChalkier": {"n": len(bk_more),
                             "favWon": sum(1 for r in bk_more if r["favWon"]),
                             "favLost": sum(1 for r in bk_more if not r["favWon"])},
        "note": "whenWeChalkier favWon% > whenBookChalkier favWon% would be the first "
                "sign our chalk-tilt is edge not noise. Accumulate before tuning.",
    }
    out = {"_doc": "NPBSide chalk-tilt ledger — model-vs-book pricing on agreement games. "
                   "Regenerated by scripts/build-chalk-ledger.py. See memory "
                   "feedback_npbside_chalk_tilt.",
           "summary": summary, "daily": daily, "rows": rows, "flips": flips}
    json.dump(out, open(OUT, "w"), ensure_ascii=False, indent=2)
    print(f"Wrote {OUT}")
    print(f"  agreement games: {summary['nAgreementGames']}  flips: {summary['nFlipGames']}  "
          f"mean gap {summary['meanGapPp']:+.1f}pp  range {summary['gapRangePp']}")
    print(f"  when WE chalkier: {summary['whenWeChalkier']['favWon']}-"
          f"{summary['whenWeChalkier']['favLost']} (fav W-L)")
    print(f"  when BOOK chalkier: {summary['whenBookChalkier']['favWon']}-"
          f"{summary['whenBookChalkier']['favLost']} (fav W-L)")

if __name__ == "__main__":
    main()
